// SPDX-FileCopyrightText: 2025 Semiotic AI, Inc.
//
// SPDX-License-Identifier: Apache-2.0

//! Correspondence tests between the Lean protocol model and the production
//! parser.
//!
//! The fixture file is generated by the Lean model in `verification/`
//! (`lake exe gen_vectors`), which proves round-trip and canonicality
//! theorems for the modeled CCTP v2 message format and self-checks every
//! vector against the model before emitting it. These tests assert that the
//! production Rust parser agrees with the model's verdicts: accepted vectors
//! parse to exactly the modeled fields and re-encode byte-for-byte; rejected
//! vectors fail to parse for the modeled reason.
//!
//! If a test here fails after a protocol change, update the Lean model and
//! regenerate the fixtures — see `verification/README.md`.

use alloy_primitives::{keccak256, Bytes, FixedBytes, U256};
use cctp_rs::{DomainId, FinalityThreshold, ParsedV2Message, TransferMode};
use serde::Deserialize;

const VECTORS_JSON: &str = include_str!("fixtures/lean/cctp_v2_vectors.json");

#[derive(Deserialize)]
struct Fixtures {
    domain_vectors: Vec<DomainVector>,
    finality_vectors: Vec<FinalityVector>,
    transfer_mode_vectors: Vec<TransferModeVector>,
    accept_message_vectors: Vec<AcceptVector>,
    reject_message_vectors: Vec<RejectVector>,
}

#[derive(Deserialize)]
struct DomainVector {
    #[serde(rename = "u32")]
    value: u32,
    valid: bool,
    name: Option<String>,
    is_evm: Option<bool>,
}

#[derive(Deserialize)]
struct FinalityVector {
    #[serde(rename = "u32")]
    value: u32,
    valid: bool,
    name: Option<String>,
}

#[derive(Deserialize)]
struct TransferModeVector {
    mode: String,
    min_finality_threshold: u32,
    is_fast: bool,
    max_fee: String,
    hook_data: Option<String>,
}

#[derive(Deserialize)]
struct AcceptVector {
    name: String,
    raw: String,
    header: HeaderVector,
    body: BodyVector,
    derived: DerivedVector,
}

#[derive(Deserialize)]
struct HeaderVector {
    version: u32,
    source_domain: u32,
    source_domain_name: String,
    destination_domain: u32,
    destination_domain_name: String,
    nonce: String,
    sender: String,
    recipient: String,
    destination_caller: String,
    min_finality_threshold: u32,
    finality_threshold_executed: u32,
}

#[derive(Deserialize)]
struct BodyVector {
    version: u32,
    burn_token: String,
    mint_recipient: String,
    amount: String,
    message_sender: String,
    max_fee: String,
    fee_executed: String,
    expiration_block: String,
    hook_data: String,
}

#[derive(Deserialize)]
struct DerivedVector {
    message_len_bytes: usize,
    has_placeholder_nonce: bool,
    is_permissionless: bool,
    requested_finality: Option<String>,
    attested_finality: Option<String>,
    is_fast_transfer: bool,
    has_hooks: bool,
}

#[derive(Deserialize)]
struct RejectVector {
    name: String,
    raw: String,
    reject_kind: String,
}

fn fixtures() -> Fixtures {
    serde_json::from_str(VECTORS_JSON).expect("Lean fixture JSON should deserialize")
}

fn bytes_of_hex(name: &str, hex: &str) -> Vec<u8> {
    alloy_primitives::hex::decode(hex)
        .unwrap_or_else(|e| panic!("vector {name}: bad hex in fixture: {e}"))
}

fn u256_of_dec(name: &str, dec: &str) -> U256 {
    U256::from_str_radix(dec, 10)
        .unwrap_or_else(|e| panic!("vector {name}: bad decimal in fixture: {e}"))
}

fn serde_name<T: serde::Serialize>(value: &T) -> String {
    match serde_json::to_value(value).expect("serializable") {
        serde_json::Value::String(s) => s,
        other => panic!("expected string serialization, got {other}"),
    }
}

/// The production `DomainId::from_u32` table must match the Lean model's
/// `DomainId.fromU32` exactly: same accepted values, same names, same
/// `is_evm` classification, and `as_u32` must invert the conversion.
#[test]
fn domain_id_conversion_matches_lean_model() {
    let fixtures = fixtures();
    assert!(!fixtures.domain_vectors.is_empty());

    for vector in &fixtures.domain_vectors {
        let parsed = DomainId::from_u32(vector.value);
        match (vector.valid, parsed) {
            (true, Some(domain)) => {
                assert_eq!(
                    domain.as_u32(),
                    vector.value,
                    "domain {}: as_u32 must invert from_u32",
                    vector.value
                );
                assert_eq!(
                    serde_name(&domain),
                    *vector.name.as_ref().expect("valid vector carries name"),
                    "domain {}: serde name must match the Lean model",
                    vector.value
                );
                assert_eq!(
                    domain.is_evm(),
                    vector.is_evm.expect("valid vector carries is_evm"),
                    "domain {}: is_evm must match the Lean model",
                    vector.value
                );
            }
            (false, None) => {}
            (expected, got) => panic!(
                "domain {}: Lean model says valid={expected}, production parser returned {got:?}",
                vector.value
            ),
        }
    }
}

/// The production `FinalityThreshold::from_u32` must accept exactly the
/// values the Lean model accepts (1000 and 2000) and reject everything else.
#[test]
fn finality_threshold_conversion_matches_lean_model() {
    let fixtures = fixtures();
    assert!(!fixtures.finality_vectors.is_empty());

    for vector in &fixtures.finality_vectors {
        let parsed = FinalityThreshold::from_u32(vector.value);
        match (vector.valid, parsed) {
            (true, Some(threshold)) => {
                assert_eq!(threshold.as_u32(), vector.value);
                assert_eq!(
                    serde_name(&threshold),
                    *vector.name.as_ref().expect("valid vector carries name"),
                    "threshold {}: serde name must match the Lean model",
                    vector.value
                );
            }
            (false, None) => {}
            (expected, got) => panic!(
                "threshold {}: Lean model says valid={expected}, production parser returned {got:?}",
                vector.value
            ),
        }
    }
}

/// The production `TransferMode` dispatch table (finality threshold, maxFee,
/// hook data per variant) must match the Lean model's dispatch theorems.
#[test]
fn transfer_mode_dispatch_matches_lean_model() {
    let fixtures = fixtures();
    assert!(!fixtures.transfer_mode_vectors.is_empty());

    for vector in &fixtures.transfer_mode_vectors {
        let max_fee = u256_of_dec(&vector.mode, &vector.max_fee);
        let hook_data = vector
            .hook_data
            .as_ref()
            .map(|hex| Bytes::from(bytes_of_hex(&vector.mode, hex)));

        let mode = match (vector.mode.as_str(), hook_data.clone()) {
            ("standard", None) => TransferMode::Standard,
            ("fast", None) => TransferMode::Fast { max_fee },
            ("standard_with_hook", Some(hook_data)) => TransferMode::StandardWithHook { hook_data },
            ("fast_with_hook", Some(hook_data)) => {
                TransferMode::FastWithHook { max_fee, hook_data }
            }
            (other, hook) => panic!("unexpected mode vector: {other} (hook: {hook:?})"),
        };

        assert_eq!(
            mode.finality_threshold().as_u32(),
            vector.min_finality_threshold,
            "mode {}: finality threshold wire value must match the Lean model",
            vector.mode
        );
        assert_eq!(mode.is_fast(), vector.is_fast, "mode {}", vector.mode);
        assert_eq!(mode.max_fee(), max_fee, "mode {}", vector.mode);
        assert_eq!(
            mode.hook_data().cloned(),
            hook_data,
            "mode {}: hook data must match the Lean model",
            vector.mode
        );
    }
}

/// Every byte string the Lean model accepts must parse in production to
/// exactly the modeled fields, re-encode byte-for-byte, and hash to
/// `keccak256(raw)`.
#[test]
fn accepted_messages_parse_to_lean_model_fields() {
    let fixtures = fixtures();
    assert!(!fixtures.accept_message_vectors.is_empty());

    for vector in &fixtures.accept_message_vectors {
        let name = &vector.name;
        let raw = bytes_of_hex(name, &vector.raw);

        let parsed = ParsedV2Message::parse(&raw).unwrap_or_else(|e| {
            panic!("vector {name}: Lean model accepts, production rejects: {e}")
        });
        assert_eq!(
            ParsedV2Message::decode(&raw).as_ref(),
            Some(&parsed),
            "vector {name}: decode and parse must agree"
        );

        // Header fields.
        let header = &vector.header;
        assert_eq!(
            parsed.header.version, header.version,
            "vector {name}: header version"
        );
        assert_eq!(
            parsed.header.source_domain.as_u32(),
            header.source_domain,
            "vector {name}: source domain"
        );
        assert_eq!(
            serde_name(&parsed.header.source_domain),
            header.source_domain_name,
            "vector {name}: source domain name"
        );
        assert_eq!(
            parsed.header.destination_domain.as_u32(),
            header.destination_domain,
            "vector {name}: destination domain"
        );
        assert_eq!(
            serde_name(&parsed.header.destination_domain),
            header.destination_domain_name,
            "vector {name}: destination domain name"
        );
        for (field, actual, expected) in [
            ("nonce", parsed.header.nonce, &header.nonce),
            ("sender", parsed.header.sender, &header.sender),
            ("recipient", parsed.header.recipient, &header.recipient),
            (
                "destination_caller",
                parsed.header.destination_caller,
                &header.destination_caller,
            ),
        ] {
            let expected: FixedBytes<32> = expected
                .parse()
                .unwrap_or_else(|e| panic!("vector {name}: bad {field} hex: {e}"));
            assert_eq!(actual, expected, "vector {name}: header {field}");
        }
        assert_eq!(
            parsed.header.min_finality_threshold, header.min_finality_threshold,
            "vector {name}: min finality"
        );
        assert_eq!(
            parsed.header.finality_threshold_executed, header.finality_threshold_executed,
            "vector {name}: executed finality"
        );

        // Body fields.
        let body = &vector.body;
        assert_eq!(
            parsed.body.version, body.version,
            "vector {name}: body version"
        );
        for (field, actual, expected) in [
            ("burn_token", parsed.body.burn_token, &body.burn_token),
            (
                "mint_recipient",
                parsed.body.mint_recipient,
                &body.mint_recipient,
            ),
            (
                "message_sender",
                parsed.body.message_sender,
                &body.message_sender,
            ),
        ] {
            let expected: FixedBytes<32> = expected
                .parse()
                .unwrap_or_else(|e| panic!("vector {name}: bad {field} hex: {e}"));
            assert_eq!(actual, expected, "vector {name}: body {field}");
        }
        for (field, actual, expected) in [
            ("amount", parsed.body.amount, &body.amount),
            ("max_fee", parsed.body.max_fee, &body.max_fee),
            ("fee_executed", parsed.body.fee_executed, &body.fee_executed),
            (
                "expiration_block",
                parsed.body.expiration_block,
                &body.expiration_block,
            ),
        ] {
            assert_eq!(
                actual,
                u256_of_dec(name, expected),
                "vector {name}: body {field}"
            );
        }
        assert_eq!(
            parsed.body.hook_data,
            Bytes::from(bytes_of_hex(name, &body.hook_data)),
            "vector {name}: hook data"
        );

        // Derived flags the SDK exposes to consumers.
        let derived = &vector.derived;
        assert_eq!(
            raw.len(),
            derived.message_len_bytes,
            "vector {name}: length"
        );
        assert_eq!(
            parsed.header.has_placeholder_nonce(),
            derived.has_placeholder_nonce,
            "vector {name}: placeholder nonce"
        );
        assert_eq!(
            parsed.header.is_permissionless(),
            derived.is_permissionless,
            "vector {name}: permissionless"
        );
        assert_eq!(
            parsed.header.requested_finality().map(|t| serde_name(&t)),
            derived.requested_finality,
            "vector {name}: requested finality"
        );
        assert_eq!(
            parsed.header.attested_finality().map(|t| serde_name(&t)),
            derived.attested_finality,
            "vector {name}: attested finality"
        );
        assert_eq!(
            parsed.body.is_fast_transfer(),
            derived.is_fast_transfer,
            "vector {name}: fast transfer flag"
        );
        assert_eq!(
            parsed.body.has_hooks(),
            derived.has_hooks,
            "vector {name}: hooks flag"
        );

        // The canonicality contract: re-encoding reproduces the raw bytes,
        // so the parsed value determines the on-chain message hash.
        assert_eq!(
            parsed.encode().as_ref(),
            raw.as_slice(),
            "vector {name}: re-encode must reproduce the canonical bytes"
        );
        assert_eq!(
            parsed.message_hash(),
            keccak256(&raw),
            "vector {name}: message hash must be keccak256 of the raw bytes"
        );
    }
}

/// Every byte string the Lean model rejects must be rejected by the
/// production parser too, with an error naming the modeled reason.
#[test]
fn rejected_messages_fail_to_parse() {
    let fixtures = fixtures();
    assert!(!fixtures.reject_message_vectors.is_empty());

    for vector in &fixtures.reject_message_vectors {
        let name = &vector.name;
        let raw = bytes_of_hex(name, &vector.raw);

        assert!(
            ParsedV2Message::decode(&raw).is_none(),
            "vector {name}: Lean model rejects, production decode accepted"
        );
        let error = ParsedV2Message::parse(&raw)
            .expect_err(&format!(
                "vector {name}: Lean model rejects, production parse accepted"
            ))
            .to_string();

        let expected_fragment = match vector.reject_kind.as_str() {
            "too_short_header" => "header requires at least",
            "too_short_body" => "burn message body requires at least",
            // The production parser reports unknown domains as a header
            // decode failure without naming the field.
            "unknown_source_domain" | "unknown_destination_domain" => "failed to decode header",
            "non_canonical_burn_token" => "burn_token",
            "non_canonical_mint_recipient" => "mint_recipient",
            "non_canonical_message_sender" => "message_sender",
            other => panic!("vector {name}: unknown reject kind {other}"),
        };
        assert!(
            error.contains(expected_fragment),
            "vector {name}: error should mention '{expected_fragment}', got: {error}"
        );
    }
}
